// Generated by CoffeeScript 1.6.3
var ws = new (require("ws").Server)({
  port: 8080
});

ws.on("connection", function(sock) {
  sock.on("message", function(msg, data) {
    process.stdout.write(data.buffer);
  });
});

